#define BLAD -1
#define OK 1

#define DOMYSLNY_ZASIEG 1

#define SILA_OWCY 4
#define INICJATYWA_OWCY 4

#define SILA_WILKA 9
#define INICJATYWA_WILKA 5

#define SILA_LISA 3
#define INICJATYWA_LISA 7

#define SILA_ZOLWIA 2
#define INICJATYWA_ZOLWIA 1
#define ZOLW_MAKSYMALNA_ODBIJANA_SILA 5
#define ZOLW_SZANSA_NA_BRAK_AKCJI 75

#define SILA_ANTYLOPY 4
#define INICJATYWA_ANTYLOPY 4
#define ZASIEG_ANTYLOPY 2
#define ANTYLOPA_SZANSA_NA_UCIECZKE 50

#define SILA_CZLOWIEKA 5
#define INICJATYWA_CZLOWIEKA 4
#define CZLOWIEK_PUNKT_STARTOWY 0
#define LIMIT_TUR_NIESMIERTELNOSCI 5

#define SZANSA_NA_ROZPRZESTRZENIENIE 10
#define INICJATYWA_ROSLINY 0
#define ILOSC_PROB_ROSLINY 1
#define SILA_TRAWY 0
#define ILOSC_PROB_MLECZA 3
#define SILA_MLECZA 0 
#define SILA_GUARANY 0
#define GUARANA_WZMOCNIENIE 3
#define SILA_WILCZYCH_JAGOD 99
#define SILA_BARSZCZU_SOSNOWSKIEGO 10

#define STRZALKA_GORA 72
#define STRZALKA_DOL 80
#define STRZALKA_LEWO 75
#define STRZALKA_PRAWO 77

#define POLNOC 0
#define WSCHOD 1
#define POLUDNIE 2
#define ZACHOD 3

#define WALKA 10
#define BEZ_RUCHU 20
#define UCIECZKA 30
#define SMIERC 40